services:
  dynamodb-local:
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ./data"
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    ports:
      - "8000:8000"
    volumes:
     - "./docker/dynamodb:/home/dynamodblocal/data"
    working_dir: /home/dynamodblocal

  fastapi:
    build: .
    container_name: fastapi
    ports:
      - "8001:8001"
    depends_on:
      - dynamodb-local
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000