AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Address Matching API with Lambda and API Gateway connected to SageMaker

Parameters:
  SageMakerEndpointName:
    Type: String
    Description: Name of the SageMaker endpoint for address matching
    Default: address-matching-endpoint
  LambdaFunctionName:
    Type: String
    Description: Name of the Lambda function
    Default: address-matching-lambda
  ApiStageName:
    Type: String
    Description: Name of the API Gateway stage
    Default: prod

Resources:
  # Lambda Function
  AddressMatchingFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: !Ref LambdaFunctionName
      CodeUri: ./lambda/
      Handler: lambda_function.lambda_handler
      Runtime: python3.9
      Timeout: 30
      MemorySize: 128
      Environment:
        Variables:
          SAGEMAKER_ENDPOINT_NAME: !Ref SageMakerEndpointName
      Policies:
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
                - sagemaker:InvokeEndpoint
              Resource: !Sub arn:aws:sagemaker:${AWS::Region}:${AWS::AccountId}:endpoint/${SageMakerEndpointName}
      Events:
        ApiEvent:
          Type: Api
          Properties:
            Path: /match-addresses
            Method: post
            RestApiId: !Ref AddressMatchingApi

  # API Gateway
  AddressMatchingApi:
    Type: AWS::Serverless::Api
    Properties:
      Name: AddressMatchingApi
      StageName: !Ref ApiStageName
      Cors:
        AllowMethods: "'GET,POST,OPTIONS'"
        AllowHeaders: "'Content-Type,X-Amz-Date,Authorization,X-Api-Key,X-Amz-Security-Token'"
        AllowOrigin: "'*'"
      Auth:
        DefaultAuthorizer: NONE
        AddDefaultAuthorizerToCorsPreflight: false

Outputs:
  AddressMatchingFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt AddressMatchingFunction.Arn
  AddressMatchingApi:
    Description: "API Gateway endpoint URL"
    Value: !Sub "https://${AddressMatchingApi}.execute-api.${AWS::Region}.amazonaws.com/${ApiStageName}/match-addresses"
  ApiGatewayConsoleURL:
    Description: "Console URL to view the API Gateway"
    Value: !Sub "https://console.aws.amazon.com/apigateway/home?region=${AWS::Region}#/apis/${AddressMatchingApi}/resources"