services:
  dynamodb-local:
    image: amazon/dynamodb-local
    container_name: dynamodb-local
    networks:
      - dynamodb-local
    ports:
      - "8000:8000"
    volumes:
      - dynamodata:/home/dynamodblocal
    working_dir: /home/dynamodblocal
    command: "-jar DynamoDBLocal.jar -sharedDb -dbPath ."  

  express:
    build: .
    container_name: express
    ports:
      - "3000:3000"
    depends_on:
      - dynamodb-local
    environment:
      - DYNAMODB_ENDPOINT=http://dynamodb-local:8000

networks:
  dynamodb-local:
    name: dynamodb-local

volumes:
  dynamodata: {}